<?php
class RptInvoiceList extends CReport {
	public $show_report_title = false;

	protected function fields() {
		$arr = array(
            'number'=>array('label'=> 'Number','width'=>20,'align'=>'L'),
            'dates'=>array('label'=> 'Date','width'=>15,'align'=>'C'),
            'customer_account'=>array('label'=> 'Customer Account','width'=>20,'align'=>'L'),
            'payment_term'=>array('label'=> 'Payment Term','width'=>15,'align'=>'L'),
            'customer_po_no'=>array('label'=> 'Customer Po No','width'=>15,'align'=>'L'),
            'sales_order_no'=>array('label'=> 'Sales Order No','width'=>15,'align'=>'L'),
            'sales_order_date'=>array('label'=> 'Sales Order Date','width'=>15,'align'=>'C'),
            'ship_via'=>array('label'=> 'Ship Via','width'=>15,'align'=>'L'),
            'salesperson'=>array('label'=> 'Salesperson','width'=>20,'align'=>'L'),
			'invoice_company'=>array('label'=> 'Invoice Company','width'=>30,'align'=>'L'),
            'invoice_address'=>array('label'=> 'Invoice Address','width'=>40,'align'=>'L'),
            'invoice_tel'=>array('label'=> 'Invoice Tel','width'=>20,'align'=>'L'),
			'delivery_company'=>array('label'=> 'Delivery Company','width'=>30,'align'=>'L'),
            'delivery_address'=>array('label'=> 'Delivery Address','width'=>40,'align'=>'L'),
            'delivery_tel'=>array('label'=> 'Delivery Tel','width'=>20,'align'=>'L'),
			
            'product_code'=>array('label'=> 'Product Code','width'=>15,'align'=>'L'),
            'description'=>array('label'=> 'Description','width'=>15,'align'=>'L'),
            'quantity'=>array('label'=> 'Quantity','width'=>10,'align'=>'R'),
            'unit_price'=>array('label'=> 'Unit Price','width'=>10,'align'=>'R'),
            'amount'=>array('label'=> 'Amount','width'=>10,'align'=>'R'),
			
            'disc'=>array('label'=> 'GST%','width'=>10,'align'=>'R'),
            'sub_total'=>array('label'=> 'Sub Total','width'=>10,'align'=>'R'),
            'gst'=>array('label'=> 'Gst Amount','width'=>10,'align'=>'L'),
            'total_amount'=>array('label'=> 'Total Amount','width'=>10,'align'=>'L'),
            'generated_by'=>array('label'=> 'Generated By','width'=>20,'align'=>'L'),
		);
		/* 由於無法調用Yii::t所以不使用
		$arr = array(
            'number'=>array('label'=>Yii::t('invoice','Number'),'width'=>20,'align'=>'L'),
            'dates'=>array('label'=>Yii::t('invoice','Date'),'width'=>15,'align'=>'C'),
            'customer_account'=>array('label'=>Yii::t('invoice','Customer Account'),'width'=>20,'align'=>'L'),
            'payment_term'=>array('label'=>Yii::t('invoice','Payment Term'),'width'=>15,'align'=>'L'),
            'customer_po_no'=>array('label'=>Yii::t('invoice','Customer Po No'),'width'=>15,'align'=>'L'),
            'sales_order_no'=>array('label'=>Yii::t('invoice','Sales Order No'),'width'=>15,'align'=>'L'),
            'sales_order_date'=>array('label'=>Yii::t('invoice','Sales Order Date'),'width'=>15,'align'=>'C'),
            'ship_via'=>array('label'=>Yii::t('invoice','Ship Via'),'width'=>15,'align'=>'L'),
            'salesperson'=>array('label'=>Yii::t('invoice','Salesperson'),'width'=>20,'align'=>'L'),
			'invoice_company'=>array('label'=>Yii::t('invoice','Invoice Company'),'width'=>30,'align'=>'L'),
            'invoice_address'=>array('label'=>Yii::t('invoice','Invoice Address'),'width'=>40,'align'=>'L'),
            'invoice_tel'=>array('label'=>Yii::t('invoice','Invoice Tel'),'width'=>20,'align'=>'L'),
			'delivery_company'=>array('label'=>Yii::t('invoice','Delivery Company'),'width'=>30,'align'=>'L'),
            'delivery_address'=>array('label'=>Yii::t('invoice','Delivery Address'),'width'=>40,'align'=>'L'),
            'delivery_tel'=>array('label'=>Yii::t('invoice','Delivery Tel'),'width'=>20,'align'=>'L'),
			
            'product_code'=>array('label'=>Yii::t('invoice','Product Code'),'width'=>15,'align'=>'L'),
            'description'=>array('label'=>Yii::t('invoice','Description'),'width'=>15,'align'=>'L'),
            'quantity'=>array('label'=>Yii::t('invoice','Quantity'),'width'=>10,'align'=>'R'),
            'unit_price'=>array('label'=>Yii::t('invoice','Unit Price'),'width'=>10,'align'=>'R'),
            'amount'=>array('label'=>Yii::t('invoice','Amount'),'width'=>10,'align'=>'R'),
			
            'disc'=>array('label'=>Yii::t('invoice','Disc'),'width'=>10,'align'=>'R'),
            'sub_total'=>array('label'=>Yii::t('invoice','Sub Total'),'width'=>10,'align'=>'R'),
            'gst'=>array('label'=>Yii::t('invoice','Gst'),'width'=>10,'align'=>'L'),
            'total_amount'=>array('label'=>Yii::t('invoice','Total Amount'),'width'=>10,'align'=>'L'),
            'generated_by'=>array('label'=>Yii::t('invoice','Generated By'),'width'=>20,'align'=>'L'),
		);
		*/
		
		return $arr;
	}

	public function genReport() {
		$tmp = array();
		$last_no = '';
		foreach ($this->data as $row) {
			$tmp[] = $row;
		}
		$this->data = $tmp;
		return $this->exportExcel();
	}
}
?>
